version: '3'
services:
  client:
    build:
      context: ./client/koreigners
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    depends_on:
      - database

  database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
